name: "[Repo CI] Terraform with GCP"

on:
  pull_request:

jobs:
  terraform-gcp:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./gcp

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.2

    - name: Initialize Terraform
      run: terraform init
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Validate Terraform
      run: terraform validate
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Format Terraform
      run: terraform fmt -check -recursive
      continue-on-error: true
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Set up TFLint
      uses: terraform-linters/setup-tflint@v3

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint --disable-rule terraform_required_version
