name: "[Repo CI] Terraform with GCP"

on:
  pull_request:

jobs:
  terraform-gcp:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./gcp

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.2

    - name: Terraform Init
      run: terraform init
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Terraform Validate
      run: terraform validate
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Terraform Format
      run: terraform fmt -check -recursive
      continue-on-error: true
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: TFLint Setup
      uses: terraform-linters/setup-tflint@v3

    - name: Run TFLint
      run: |
        tflint --init
        tflint --disable-rule=terraform_required_version \
               --disable-rule=terraform_required_providers

    - name: Terraform Plan
      run: terraform plan -no-color
      continue-on-error: true
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
