name: "[Repo CI] Integrate Terraform with Docker"

on:
  pull_request:
    paths:
      - "docker/**"

jobs:
  docker:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./docker

    steps:
      - name: Checkout base branch
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.2

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        id: validate
        run: terraform validate

      - name: Format Terraform
        id: format
        continue-on-error: true
        run: terraform fmt -check -recursive

      - name: Set up TFLint
        uses: terraform-linters/setup-tflint@v3

      - name: Lint Terraform
        id: lint
        run: |
          tflint --init
          tflint --disable-rule=terraform_required_version \
                 --disable-rule=terraform_required_providers

      - name: Plan Terraform
        id: plan
        continue-on-error: true
        run: terraform plan -no-color

      - name: Output Terraform
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.format.outcome }}\`
            #### Terraform Lint 🔨\`${{ steps.lint.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>

            \`\`\`\n
            ${{ steps.validate.outputs.stdout }}
            \`\`\`

            </details>

            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`tf\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
