name: "[Repo CI] Terraform Push with GCP"

on:
  push:
    branches:
      - main
    paths:
      - "gcp/**"

jobs:
  gcp:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./gcp

    steps:
      - name: Checkout base branch
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.2

      - name: Initialize Terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: terraform init

      - name: Validate Terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: terraform validate

      - name: Format Terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: terraform fmt -check -recursive

      - name: Set up TFLint
        uses: terraform-linters/setup-tflint@v3

      - name: Lint Terraform
        run: |
          tflint --init
          tflint --disable-rule=terraform_required_version \
                 --disable-rule=terraform_required_providers

      - name: Plan Terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: terraform plan -no-color

      - name: Apply Terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: terraform apply -auto-approve
